server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 111.92.242.17
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: false