server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 111.92.242.17
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: false
