server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
          locator:
            enabled: true                     #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**            # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route   #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/create/**         # 断言，路径相匹配的进行路由
                                              # [ After ]                       // 指定日期之后
                                              # [ Before ]                      // 指定日期之前
                                              # [ Between ]                     // 在指定日期之间
                                              # [ Cookie ]                      // 匹配指定cookie的值
                                              # [ Header ]                      // 匹配指定请求头的值
                                              # [ Host ]                        // 匹配请求的host
                                              # [ Method ]                      // 匹配请求的方法
                                              # [ Path ]                        // 匹配请求的路径
                                              # [ Query ]                       // 匹配请求的参数
                                              # [ ReadBodyPredicateFactory ]    // 匹配请求体
                                              # [ RemoteAddr ]                  // 匹配请求的远程地址
                                              # [ Weight ]                      // 匹配请求的权重
                                              # [ CloudFoundryRouteService ]    // 匹配CloudFoundry路由服务
eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:7001/eureka, http://127.0.0.1:7002/eureka, http://127.0.0.1:7003/eureka
