server:
  port: 80

#\u670D\u52A1\u522B\u540D----\u6CE8\u518Czookeeper\u5230\u6CE8\u518C\u4E2D\u5FC3\u540D\u79F0
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 111.92.242.17:2181
