server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka, http://127.0.0.1:7002/eureka, http://127.0.0.1:7003/eureka
logging:
  level:
    # feign日志以什么级别监控哪个接口
    vio.vin.cloudconsumerfeignorder80.service.PaymentFeignService: debug
feign:
  client:
    config:
      default:
          connectTimeout: 3000
          readTimeout: 3000